# Generated by Django 4.2.6 on 2023-11-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0003_esame_unita_misura'),
    ]

    operations = [
        migrations.AddField(
            model_name='esame',
            name='valore',
            field=models.IntegerField(null=True),
        ),
    ]
